apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 190489742470.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 190489742470.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: a329873e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
